//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimsPackageQuery
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataItem()
        {
            this.DataItemDetails = new HashSet<DataItemDetail>();
        }
    
        public int ID { get; set; }
        public string ERROR { get; set; }
        public string URL { get; set; }
        public string S3FILENAME { get; set; }
        public string PREVIEWURL { get; set; }
        public string ARTIST { get; set; }
        public Nullable<int> IMAGEID { get; set; }
        public string IMAGEEXTENSION { get; set; }
        public string DESCRIPTION { get; set; }
        public string CATEGORY { get; set; }
        public Nullable<int> GAME { get; set; }
        public Nullable<bool> FREE { get; set; }
        public Nullable<bool> WASNOTFREE { get; set; }
        public string PUBLISHDATE { get; set; }
        public string REVISION { get; set; }
        public Nullable<int> CREATORMEMBERID { get; set; }
        public string TITLE { get; set; }
        public string S3FILETYPE { get; set; }
        public Nullable<int> CATEGORYID { get; set; }
        public Nullable<int> FILEID { get; set; }
        public Nullable<bool> DOWNLOADED { get; set; }
        public string FILENAME { get; set; }
        public Nullable<int> FILESIZE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataItemDetail> DataItemDetails { get; set; }
    }
}
