//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimsPackageQuery
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TheSimsDownloaderEntities : DbContext
    {
        public TheSimsDownloaderEntities()
            : base("name=TheSimsDownloaderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Datum> Data { get; set; }
        public virtual DbSet<DataItem> DataItems { get; set; }
        public virtual DbSet<DataItemDetail> DataItemDetails { get; set; }
    }
}
